#prod env
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111111111:3306/zzx?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: 111111
    password: 11111111
  http:
      multipart:
        enabled: true
        max-file-size: 50Mb
        max-request-size: 100Mb


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.zzx.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false #配置的缓存的全局开关
    lazyLoadingEnabled: false #延时加载的开关
    multipleResultSetsEnabled: false #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    call-setters-on-nulls: false
    return-instance-for-empty-row: false


logging:
  level: info
server:
  port: 30074
  context-path: /generatecode/